<?php

use App\Imports\ProductsImport;
use App\Product;
use Illuminate\Database\Seeder;
use Maatwebsite\Excel\Facades\Excel;

class ProductsTableSeeder extends Seeder
{
    protected $products = [
        [
            "id" => 1,
            "name" => "Hojaldra de jamón y queso",
            "description" => "1 pieza",
            "ingredients" => "jamón",
            "image" => "public/products/plZXSjboICXf9sUaR888t4kK8ln7dWwZmYOXr9N8.jpeg",
            "price" => 70000,
            "available" => 1,
            "available_time" => null,
            "favorite" => 1,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-27 00:22:34"
        ],
        [
            "id" => 2,
            "name" => "Hojaldra de jamón y queso",
            "description" => "24 piezas",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 1595000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 3,
            "name" => "Hojaldra de jamón y queso",
            "description" => "48 piezas",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 3190000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 4,
            "name" => "Hojaldra de rajas",
            "description" => "24 piezas",
            "ingredients" => "rajas",
            "image" => "/breads/Cuernito.png",
            "price" => 1710000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 5,
            "name" => "Hojaldra de rajas",
            "description" => "48 piezas",
            "ingredients" => "rajas",
            "image" => "/breads/Cuernito.png",
            "price" => 3420000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 6,
            "name" => "Hojaldra de pollo",
            "description" => "24 piezas",
            "ingredients" => "pollo",
            "image" => "/breads/Cuernito.png",
            "price" => 1710000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 7,
            "name" => "Hojaldra de pollo",
            "description" => "48 piezas",
            "ingredients" => "pollo",
            "image" => "/breads/Cuernito.png",
            "price" => 3420000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 8,
            "name" => "Hojaldra de atún",
            "description" => "24 piezas",
            "ingredients" => "atún",
            "image" => "/breads/Cuernito.png",
            "price" => 1710000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 9,
            "name" => "Hojaldra de atún",
            "description" => "48 piezas",
            "ingredients" => "atún",
            "image" => "/breads/Cuernito.png",
            "price" => 3420000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 10,
            "name" => "Hojaldra Especial",
            "description" => "1 pza",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 135000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 11,
            "name" => "Volován de jamón y queso",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 12,
            "name" => "Volován de pollo",
            "description" => "",
            "ingredients" => "pollo",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 13,
            "name" => "Volován de atún",
            "description" => "",
            "ingredients" => "atún",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 14,
            "name" => "Volován de horizo",
            "description" => "",
            "ingredients" => "chorizo",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 15,
            "name" => "Volován hawaiiano",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 16,
            "name" => "Volován de rajas",
            "description" => "",
            "ingredients" => "rajas",
            "image" => "/breads/Cuernito.png",
            "price" => 115000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 17,
            "name" => "Bomba preparada",
            "description" => "",
            "ingredients" => "frijol",
            "image" => "/breads/Cuernito.png",
            "price" => 130000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 18,
            "name" => "Bomba preparada mini",
            "description" => "",
            "ingredients" => "frijol",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 19,
            "name" => "Pambazo preparado",
            "description" => "",
            "ingredients" => "frijol",
            "image" => "/breads/Cuernito.png",
            "price" => 110000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 20,
            "name" => "Pambazo preparado mini",
            "description" => "",
            "ingredients" => "frijol",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 21,
            "name" => "Media Noche de carne polaca",
            "description" => "",
            "ingredients" => "pollo",
            "image" => "/breads/Cuernito.png",
            "price" => 150000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 22,
            "name" => "Media Noche de carne polaca mini",
            "description" => "",
            "ingredients" => "pollo",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 23,
            "name" => "Media Noche de jamón y queso",
            "description" => "24 piezas",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 1595000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 24,
            "name" => "Media Noche de jamón y queso mini",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 25,
            "name" => "Cuerno de jamón y queso",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 155000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 26,
            "name" => "Cuerno de jamón y queso mini",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 27,
            "name" => "Torta de jamón serrano mini",
            "description" => "",
            "ingredients" => "jamón serrano",
            "image" => "/breads/Cuernito.png",
            "price" => 140000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 28,
            "name" => "Serpentina de jamón y queso",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 80000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 29,
            "name" => "Canapé Vacío",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 50000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 30,
            "name" => "Canapé de jamón y queso",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 90000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 31,
            "name" => "Canapé de atún",
            "description" => "",
            "ingredients" => "atún",
            "image" => "/breads/Cuernito.png",
            "price" => 90000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 32,
            "name" => "Canapé de ensalada rusa",
            "description" => "",
            "ingredients" => "ensalada rusa",
            "image" => "/breads/Cuernito.png",
            "price" => 90000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 33,
            "name" => "Media Luna de jamón y queso",
            "description" => "",
            "ingredients" => "jamón",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 3,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 34,
            "name" => "Pambazo",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 25000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 35,
            "name" => "Media noche de sal",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 25000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 36,
            "name" => "Telera",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 25000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 37,
            "name" => "Micha",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 25000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 38,
            "name" => "Bolillo",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 25000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 39,
            "name" => "Baguette natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 185000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 40,
            "name" => "Baguette de ajonjolí",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 195000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 41,
            "name" => "Baguette de ajo/parmesano",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 255000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 42,
            "name" => "Baguette de especias italianas",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 255000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 43,
            "name" => "Tornillo natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 35000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 44,
            "name" => "Tornillo de ajonjolí",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 45000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 45,
            "name" => "Tornillo de ajo/parmesano",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 45000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 46,
            "name" => "Tornillo de especias italianas",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 45000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 47,
            "name" => "Pan molido chico",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 195000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 48,
            "name" => "Pan molido mediano",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 285000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 49,
            "name" => "Pan molido grande",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 465000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 50,
            "name" => "Pambazo mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 19000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 51,
            "name" => "Media noche de sal mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 19000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 52,
            "name" => "Telera mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 19000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 2,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 53,
            "name" => "Banderilla mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 54,
            "name" => "Bomba original mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 55,
            "name" => "Bomba de chocolate mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 56,
            "name" => "Bomba de vainilla mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 57,
            "name" => "Campechana mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 58,
            "name" => "Canilla natural mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 59,
            "name" => "Canilla con ajonjolí mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 60,
            "name" => "Cuerno mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 61,
            "name" => "Danés azucarado mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 62,
            "name" => "Dona de chocolate mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 63,
            "name" => "Dona de azúcar mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 64,
            "name" => "Dona de fresa mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 65,
            "name" => "Dona Blanca mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 66,
            "name" => "estropajo mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 67,
            "name" => "garibaldi mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 50000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 68,
            "name" => "gragea mini",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 69,
            "name" => "oreja mini natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 40000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 70,
            "name" => "oreja mini de anís",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 71,
            "name" => "oreja mini de canela",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 72,
            "name" => "Bomba original",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 73,
            "name" => "Bomba de chocolate",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 74,
            "name" => "Bomba de vainilla",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 75,
            "name" => "Budín original",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 100000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 76,
            "name" => "Budín original entero",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 1555000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 77,
            "name" => "Budín con caramelo",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 78,
            "name" => "Budín con caramelo entero",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 0,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 79,
            "name" => "Canilla natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 80,
            "name" => "Canilla con ajonjolí",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 81,
            "name" => "Canilla de agua tipo Tlacotalpan",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 145000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 82,
            "name" => "Chamuco Azucarado",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 83,
            "name" => "Chamucho natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 84,
            "name" => "Chamucho con ajonjolí",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 85,
            "name" => "Dona de chocolate",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 85000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 86,
            "name" => "Dona de azúcar",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 85000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 87,
            "name" => "Dona de fresa",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 85000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 88,
            "name" => "Dona Blanca",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 85000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 89,
            "name" => "Pay de piña por rebanada",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 130000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 90,
            "name" => "Pay de piña entero",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 820000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 91,
            "name" => "Piedra natural",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 92,
            "name" => "Piedra con chocolate",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 65000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 93,
            "name" => "Tuti con ajonjolí",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 55000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 94,
            "name" => "Bomba Tuti",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 55000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ],
        [
            "id" => 95,
            "name" => "Tuti hojaldrado",
            "description" => "",
            "ingredients" => "",
            "image" => "/breads/Cuernito.png",
            "price" => 55000,
            "available" => 0,
            "available_time" => null,
            "favorite" => 0,
            "category_id" => 1,
            "created_at" => "2020-01-24 18:09:52",
            "updated_at" => "2020-01-24 18:09:52"
        ]
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // I need to export local products table from DB cuz it does not find products .xlsx
//        Excel::import(new ProductsImport, './products.xlsx');
        collect($this->products)->map(function($current) {
            $product = collect($current);
            Product::create([
                "name" => $product->get('name'),
                "description" => $product->get('description'),
                "ingredients" => $product->get('ingredients'),
                "image" => $product->get('image'),
                "price" => $product->get('price'),
                "available" => $product->get('available'),
                "available_time" => $product->get('available_time'),
                "favorite" => $product->get('favorite'),
                "category_id" => $product->get('category_id'),
            ]);
        });
    }
}
